### ISSUE TITLE
TODO: Add a textbox output for the # of comparisons and swaps so far

### ISSUE THREAD

**Issue by kulkuza** [kulkuza/CS342-SP2017-VIDSort#13]
You can put them as 0 and 0 for now. Later there will be .getComparisons() and .getSwaps() for the VisualArray. So while the array is sorting, the count of comparisons and swaps shown should constantly update.

**Comment by luis-garibay** [comment]
Do you want to increment the number of comparisons/swaps and have them reset whenever a new array is set?
Or keep track of the counts in sort() and set them in the GUI accordingly?

**Comment by kulkuza** [comment]
Create a textbox, so I can use the instance of the GUI and update it in the VisualArray. So gui.update(i, j) would update the visualization. And maybe gui.updateComparisonsAndSwaps(int comparisons, int swaps) would update the textbox.

**Comment by luis-garibay** [comment]
I'm on it.

**Comment by luis-garibay** [comment]
Done. Just use `gui.updateComparisonsAndSwaps(int comparisons, int swaps)`

**Comment by kulkuza** [comment]
Actually. Could you separate the two updates? gui.updateComparisons(int comparisons) and gui.updateSwaps(int swaps) since the compare() and swap() methods are separate.

**Comment by luis-garibay** [comment]
Changed
