### ISSUE TITLE
Update ViDSortGUI Usage In swap()

### ISSUE THREAD

**Issue by luis-garibay** [kulkuza/CS342-SP2017-VIDSort#19]
Instead of update(int[] arr), use update(int index1, int index2).
This allows highlighting of elements to be swapped and for delay in timing to be handled by the VisualArrayCanvas.

**Comment by kulkuza** [comment]
I get a null pointer exception in the Timer-0 thread in the swapArrayValues in the VisualArrayCanvas

**Comment by luis-garibay** [comment]
Sorry, I must have forgotten to set default values in main().
It should be good now.

**Comment by kulkuza** [comment]
Can you push the new build?
I'm still getting the same errors.

**Comment by luis-garibay** [comment]
I pushed it.
But, I must have fixed the wrong bug.
Can you post the stack trace, plz?

**Comment by kulkuza** [comment]
> Exception in thread "Timer-0" java.lang.NullPointerException
> 	at VisualArrayCanvas.swapArrayValues(VisualArrayCanvas.java:23)
> 	at ViDSortGUI.update(ViDSortGUI.java:147)
> 	at SortArray.compareAndSwap(SortArray.java:63)
> 	at BubbleSort.sort(BubbleSort.java:10)
> 	at SortArray.sort(SortArray.java:100)
> 	at CS342VIDSort$1.run(CS342VIDSort.java:37)
> 	at java.util.TimerThread.mainLoop(Timer.java:555)
> 	at java.util.TimerThread.run(Timer.java:505)

**Comment by luis-garibay** [comment]
Oops. Before you can update the array, the array needs to be set by calling ViDSortGUI.setVisualArray(int[] arr).

**Comment by kulkuza** [comment]
Hmmm. There's alot of weird colors. Replace this method in the SortArray.java and try to debug it.

```
public boolean compareAndSwap(int i, int j) {
    	if (compare(i, j) > 0) {
    		swap(i, j);
    		System.out.println("Updating GUI\n");
    		ViDSortGUI gui = ViDSortGUI.getInstance();
    		gui.setVisualArray(array);
    		gui.update(i,j);
            int speed = gui.getSelectedSpeed();
    		try {
    			TimeUnit.MILLISECONDS.sleep(speed);
    		} catch (InterruptedException e) {
    			System.out.println("Delay exception");
    		}
    		return true;
    	}
    	else {
    		return false;
    	}
    }
```

**Comment by luis-garibay** [comment]
I changed sort() a bit

```
public void sort() {
    	System.out.println("Array is sorting");
        ViDSortGUI gui = ViDSortGUI.getInstance();
        gui.setVisualArray(array);
    	algorithm.sort(this);
    	System.out.println("Array is finished sorting");

    }
```
and compareAndSwap
```
public boolean compareAndSwap(int i, int j) {
    	if (compare(i, j) > 0) {
    		swap(i, j);
    		System.out.println("Updating GUI\n");
    		ViDSortGUI gui = ViDSortGUI.getInstance();
    		gui.update(i,j);
            int speed = gui.getSelectedSpeed();
    		try {
    			TimeUnit.MILLISECONDS.sleep(speed);
    		} catch (InterruptedException e) {
    			System.out.println("Delay exception");
    		}
    		return true;
    	}
    	else {
    		return false;
    	}
    }
```

Along with a few changes to the VisualArrayCanvas code.
