### ISSUE TITLE
TODO: Compare algorithm functionality

### ISSUE THREAD

**Issue by kulkuza** [kulkuza/CS342-SP2017-VIDSort#20]
Should be implemented by Beta Release

**Comment by kulkuza** [comment]
I was thinking that since there will be left and right windows to display the sort, we should manipulate the update methods to specify which window to update it.
The update methods are: updateComparisonCount(), highlightCompare(), updateSwapCount(), updateSwap().
There would be an extra parameter that will specify which window it will update it in. 

We might have to save in as a parameter into the SortArray instance which window to display it from. So there might also be an extra parameter in the SortArray constructor that will save which window it pertains to. 

Other suggestions?

**Comment by jmei32** [comment]
Can you elaborate what each of those methods do?

**Comment by kulkuza** [comment]
They're the update methods for the GUI.

updateComparisonCount() updates the comparisons textbox.
updateSwapCount() updates the swaps textbox.
highlightCompare() is what highlights 2 elements that are being compared.
updateSwap() is what actually swaps the 2 elements in the visualization.

**Comment by luis-garibay** [comment]
I can't think of another way.
