### ISSUE TITLE
Algorithm dropdown menu switches when checked Compare checkbox and unchecked

### ISSUE THREAD

**Issue by kulkuza** [kulkuza/CS342-SP2017-VIDSort#21]
Steps to Reproduce:
1) Choose an algorithm from the dropdown. The console should output "The right algorithm is _____".
2) Check the Compare checkbox and uncheck it.
3) When choosing an algorithm from the dropdown, the console now outputs "The left algorithm is ___". The algorithm dropdown menu is now for the left instead of the right.

**Comment by luis-garibay** [comment]
Fixed.
