### ISSUE TITLE
Add labels for Algorithm, Size, and Speed module

### ISSUE THREAD

**Issue by kulkuza** [kulkuza/CS342-SP2017-VIDSort#22]
Algorithm dropdown menu should be labeled : Sorting Algorithm
Size dropdown menu should be labeled: Array Size
Speed module should be labeled: Delay(ms)

**Comment by luis-garibay** [comment]
I'm on it.

**Comment by luis-garibay** [comment]
All set.
However, I thought that "Array Size" and "Delay(ms)" might be too implementation specific.
Since the user should only be exposed to a high-level abstraction, I thought "# of Elements" and "Speed" were more appropriate.
What do you think?

**Comment by kulkuza** [comment]
That's fine. For speed however, alot of testers thought sliding to the right meant the algorithm ran faster and left was slower.

So could you hide the numbers from the speed slider (50, 150, 250, 500, etc) and reverse the values so that the leftmost part is actually 500, and the rightmost part is 50.

**Comment by luis-garibay** [comment]
All set!
