### ISSUE TITLE
Include the instance parameters for left/right in the update methods

### ISSUE THREAD

**Issue by kulkuza** [kulkuza/CS342-SP2017-VIDSort#24]
Include an extra parameter for the update functions to signify which window it is updating. 

The update methods are: updateComparisonCount(), highlightCompare(), updateSwapCount(), updateSwap().

**Comment by luis-garibay** [comment]
@kulkuza What data type are we using? Is it a string that says "right" or "left", a boolean that uses true for left, or is that undecided?

**Comment by kulkuza** [comment]
How do you determine which window to update for the sort algorithm?
You might have to add additional code for all the update functions to figure out left vs right.

**Comment by luis-garibay** [comment]
New Methods:
void setVisualArray(int[] arr, boolean canvas)
void updateSwap(int index1, int index2, boolean canvas)
void highlightCompare(int index1, int index2, boolean canvas)
void updateComparisonCount(int comparisons, boolean canvas)
void updateSwapCount(int swaps, boolean canvas)

True = right canvas
False = left canvas
