### ISSUE TITLE
Checking if the checkbox is checked

### ISSUE THREAD

**Issue by kulkuza** [kulkuza/CS342-SP2017-VIDSort#28]
Add a method so you can use an instance of the gui to see if the box is checked or not.
Ex. gui.isCompareChecked() -> bool return type

This way, we can check if the checkbox is checked in the main function, and use a separate thread to run the left side of the visualization.

**Comment by luis-garibay** [comment]
So, I sort of implemented something like this. _Sort of_.
The way you would perform the equivalent of gui.isCompareChecked() would be:
```java
gui.getMode() == ViDSortGUI.Mode.COMPARISON_MODE
```
This would return 'True' when the checkbox is checked.

Would that or gui.isCompareChecked() be easier to understand in the context of your code?

**Comment by kulkuza** [comment]
The getMode() should suffice. It's easier to read since it's actual states instead of looking at 'true' and 'false'.
