### ISSUE TITLE
Algorithm Selection

### ISSUE THREAD

**Issue by luis-garibay** [kulkuza/CS342-SP2017-VIDSort#5]
When the algorithm is selected, the value that is stored is a string.
We have to take that string ("Bubble Sort," or whatever) and choose which algorithm object to instantiate.
What do you think about the SortArray constructor using a string instead of an algorithm object as a parameter?
My thinking is that we should bury the "decision", of which algorithm object to instantiate, in abstraction.

**Comment by kulkuza** [comment]
That would work. We just need to have a wrapper class to process the string and return the corresponding algorithm class.
