### ISSUE TITLE
Updating Simulation During Sort

### ISSUE THREAD

**Issue by luis-garibay** [kulkuza/CS342-SP2017-VIDSort#6]
The sort() method calls SortArray's compareAndSwap() method.
We need to find a place to call ViDSortGUI's update() method to display the array graph thing.
So, how about the SortArray object uses the instance of ViDSortGUI and calls ViDSortGUI's update() method in the compareAndSwap() method?

You could use a one liner like:
if (compare(i, j) > 0) {
    swap(i, j);
    ViDSortGUI.getInstance().update(array);
    return true;
}

What do you think?

**Comment by kulkuza** [comment]
Yea, that was what I was thinking. Sounds fine.
